### PR TITLE
Some basic unit tests to start off with

### PR DESCRIPTION
**Pull request by mgriffin**
Here are some basic unit tests styled on vagrant-aws. There are tests for the configuration settings for windows and winrm. It checks that there are defaults set and that they can be overridden.

There is a rake task (rake spec) to run the tests too

### CODE REVIEW

**Comment by davidpellerin** [comment]
@mgriffin :good job! +1: this is nice to see

**Comment by pmorton** [comment]
woot!

**Comment by sneal** [comment]
Thanks! This is really appreciated. I tried it out and works as advertised. :shipit:

**Comment by pmorton** [comment]
@sneal Beat me to it! I was just running the tests prior to merging!

**Comment by mgriffin** [comment]
Thanks, I wasn't sure if this is what you were looking for with unit tests, but I can go ahead and work on some more now that I know.

**Pull request merged**
