### PR TITLE
Fix windows shell provisioner

### PR DESCRIPTION
**Pull request by patux**
This patch fixes issue: https://github.com/WinRb/vagrant-windows/issues/38

### CODE REVIEW

**Comment by sneal** [comment]
I'll take a look at this PR this week.

**Comment by patux** [comment]
Thanks

**Comment by sneal** [comment]
@patux Which syntax are you using in your Vagrantfiles with the shell provisioner? External script path or inline?

config.vm.provision :shell, :path => "script.ps1"
config.vm.provision :shell, :inline => "echo Hello, World"

**Comment by patux** [comment]
@sneal always external, if the script is internal there is no extensión... so that part will likely fail, cause windows will not know which interpreter to use to execute c:\tmp\vagrant-shell, but that is what is happening right now... I haven't figure out how to improve that.. but right now to me is a minor issue.... I do preffer to have something working that nothing working.

**Comment by sneal** [comment]
inline scripts will definitely fail. External scripts look like they might fail too since I believe this is pulling the file extension off the temp file and not the source script.

I'm going to work on this today, I need the ability to use inline scripts.

**Comment by patux** [comment]
mmmm I did tests  with two different scritps.. (ps1, and .bat) , and it worked.. 

Let me know if I can help

**Comment by sneal** [comment]
I used this PR and extended it to support inline shell scripts.

**Pull request closed without merging**
