### PR TITLE
Vagrant 1.1 plugin architecture

### PR DESCRIPTION
**Pull request by sneal**
Migrated plugin to the Vagrant 1.1 architecture.
1. Added chef-solo provisioner monkey patch to support running chef under new credentials on VM to fix COOK1172.
2. Fixed puppet provisioner to support new plugin architecture and cleaned it up to delegate calls to base Vagrant provisioner class when running under linux.
3. Plugin now automatically uses the winrm port specified in the port forwarding section.
4. Added english resource yaml file for error descriptions.
5. Removed dead code from communicator and consolidated functionality.

### CODE REVIEW

**Comment by pmorton** [comment]
@sneal  is this changeset backwards compatible with Vagrant 1.0?

**Comment by pmorton** [comment]
@sneal  I have answered my own question here. I think that the version bump needs to be greater. I prefer semver. This change does not maintain backwards compatibility. I think that the version bump should be to 1.0.0.

**Comment by sneal** [comment]
Makes sense.

On that topic, I'd like to keep the plugin compatible between Vagrant 1.1
and 1.2, but I'm not sure if that's possible. There are some pretty
significant changes in Vagrant 1.2 in how it handles guests and
capabilities.

**Comment by pmorton** [comment]
Yeah. I am fighting with the capabilities crazyness at the moment. I am not sure that there is an easy way to make this work. 1.1 has not been out for long. Do you see a lost of resistance in upgrading? What do you suppose the resistance is?

**Comment by sneal** [comment]
It seems people are waiting for Vagrant and other tools like test kitchen
to stabilize first before upgrading. What they have now is working and the
associated cost of upgrading a stable environment is worth it yet.

**Pull request merged**
