### PR TITLE
Compatibility with Parallels provider

### PR DESCRIPTION
**Pull request by legal90**
This commit adds compatibility with [Parallels provider](https://github.com/yshahin/vagrant-parallels)
I've checked it by myself and all existing features is working fine for this environment:
- Vagrant 1.4.0
- 'vagrant-parallels' v0.1.0
- Parallels Desktop 8 and 9
- Host: OS X 10.9
- Guest: Windows Server 2012 R2

P.s. I'm ready to support this compatibility in future.

### CODE REVIEW

**Comment by legal90** [comment]
Just one notice: while using Parallels provider, you should not put the `forwarded_port` rule into Vagrantfile, because our provider does not support port forwarding. 
But provider is detecting guest's IP correctly, you can just skip this string and everything will work fine.

**Comment by sneal** [comment]
This change looks good, thanks!

Any idea if this would work with Parallels 7? I ask because that's the version I have.

**Comment by sneal** [comment]
Released vagrant-windows 1.5 gem with Parallels support.

**Comment by legal90** [comment]
> Any idea if this would work with Parallels 7?

Unfortunatly, `vagrant-parallels` works only with Parallels Desktop 8 and higher. The reason is that `prlctl` utility in PD 7 has not option '--json' for machine-readable output and we have not done the backward compatibility yet (yshahin/vagrant-parallels#33).

**Comment by sneal** [comment]
That's OK, if I start using Parallels more often I'll probably upgrade it anyway.

**Pull request merged**
