### PR TITLE
Vagrant 1.2

### PR DESCRIPTION
**Pull request by sneal**
Added support for Vagrant 1.2 with backwards compatibility with 1.1. Various other fixes have been incorporated into this branch as well as a redesign to the chef-solo provisioner.

The chef-solo provisioner now creates a scheduled task to kick the chef run. This allows chef to be run with UAC enabled and allows for real-time output of chef output. This also sets us up for an easier migration to winrm2.0 gem using NTLM auth instead of basic.

@pmorton Can you take a look? I would like to cut a new vagrant-windows gem this week if possible. I've recently tried it out on OSX running vagrant 1.2.2 and Windows 7 host running vagrant 1.1.5.

### CODE REVIEW

**Comment by aseresun** [comment]
+1

**Comment by ferventcoder** [comment]
Looks like puppet provisioner is a bit buggy in this version (as in blows up if you try to use it). I'm not sure if #82 resolves this or not, I didn't give it a shot.

**Comment by ferventcoder** [comment]
Gave #82 a shot and it appears it is smooth sailing.

**Comment by stack72** [comment]
Any idea when this will be merged and a new gem created? _bump_

**Comment by sneal** [comment]
Should be releasing today. Going forward I'd like to release gem updates much more frequently, perhaps once a week.

**Comment by stack72** [comment]
@sneal you have made me a very happy man! thanks so much :)

**Pull request merged**
